[workspace]
resolver = "2"
members = [
    "nrf-802154-sys",
    "nrf-802154",
    "examples",
    "tests",
]

[profile.dev]
opt-level = 1               # Use slightly better optimizations.

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false

[patch.crates-io]
#openthread = { git = "https://github.com/esp-rs/openthread" }
#openthread-sys = { git = "https://github.com/esp-rs/openthread" }
