name: Check Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        run: rustup toolchain add --component=rustfmt nightly
      - name: Install clippy
        run: rustup component add clippy
      - name: Install targets
        run: rustup target add thumbv7em-none-eabi thumbv7em-none-eabihf thumbv8m.main-none-eabi thumbv8m.main-none-eabihf
      - name: Formatting
        run: cargo +nightly fmt -- --check
      - name: Checks
        run: ./ci.sh
